
CREATE DATABASE Optus;

USE Optus;

CREATE TABLE Artistas
(
	idArtista	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(200) NOT NULL
);

CREATE TABLE Albuns
(
	idAlbum				INT PRIMARY KEY IDENTITY
	,idArtista			INT FOREIGN KEY REFERENCES Artistas(idArtista)
	,Titulo				VARCHAR(200) NOT NULL
	,DataLancamento		DATE
	,Localizacao		VARCHAR(200)
	,QtsMinutos			INT NOT NULL
	,Ativo				INT NOT NULL
);

CREATE TABLE Estilos
(
	idEstilo	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(200) NOT NULL
);

CREATE TABLE AlbumEstilos
(
	idAlbum		INT FOREIGN KEY REFERENCES Albuns(idAlbum)
	,idEstilo	INT FOREIGN KEY REFERENCES Estilos(idEstilo)
);

CREATE TABLE Usuarios
(
	idUsuario	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(200) NOT NULL
	,Email		VARCHAR(200) NOT NULL
	,Senha		VARCHAR(200) NOT NULL
	,Permissao	VARCHAR(200) NOT NULL
);